version: '2.2'

services:

  opera:
    image: hadv/opera:latest
    command: --genesis /etc/opera/genesis/testnet.g --metrics --metrics.expensive --pprof --pprof.addr=0.0.0.0
    volumes:
      - ./testnet.g:/etc/opera/genesis/testnet.g

  prometheus:
    image: prom/prometheus
    depends_on:
      opera:
        condition: service_started
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      prometheus:
        condition: service_started
    volumes:
      - ./grafana.db:/var/lib/grafana/grafana.db
